name: generate animation

on:
  
  schedule:
    - cron: "0 * * * *"
  
  # permite execução manual
  workflow_dispatch:
  
  
  push:
    branches:
    - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      
      - name: escolher paleta aleatória
        id: set_palette
        run: |
          PALETTES=("github-light" "github-dark" "github-dark-dimmed")
          SELECTED=${PALETTES[$RANDOM % ${#PALETTES[@]}]}
          echo "palette=$SELECTED" >> $GITHUB_OUTPUT

      
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=${{ steps.set_palette.outputs.palette }}

      
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
